### ISSUE TITLE
Call to undefined method SquareConnect\ApiException::getCategory()

### ISSUE THREAD

**Issue by zhsolutions** [NikolaGavric94/nikolag-square#11]
Related to https://github.com/NikolaGavric94/nikolag-square/issues/10
I change line 131 to: ApiException $exception

And I get 
Call to undefined method SquareConnect\ApiException::getCategory()

**Comment by NikolaGavric94** [comment]
You are not using the latest version which fixed #10 and #11

**Comment by NikolaGavric94** [comment]
After updating dont forget to rerun migrations and to check if your published config file looks similar to [this config](https://github.com/NikolaGavric94/nikolag-square/blob/master/src/config/nikolag.php)

**Comment by NikolaGavric94** [comment]
@zhsolutions awaiting your feedback

**Comment by zhsolutions** [comment]
My Composer Config is:     "nikolag/square": "^1.1",

**Comment by NikolaGavric94** [comment]
Seems like your composer didn't fetch the newest version, remove your composer.lock file and remove vendor folder and run composer update, tell me which version does composer install?

**Comment by zhsolutions** [comment]
This is the installation output of the CL running :

composer require nikolag/square --dev
 - Installing nikolag/core (v1.0.0): Downloading (100%)
  - Installing square/connect (2.4.0): Downloading (100%)
  - Installing nikolag/square (v1.1.0): Downloading (100%)

After that the Issue #10 still present.

**Comment by NikolaGavric94** [comment]
@zhsolutions can you check does the file [SquareConfig.php](https://github.com/NikolaGavric94/nikolag-square/blob/master/src/SquareService.php) from [v1.1.0](https://github.com/NikolaGavric94/nikolag-square/releases/tag/v1.1.0) match the same file in your vendor folder?

**Comment by zhsolutions** [comment]
It Does not Match

**Comment by NikolaGavric94** [comment]
Hmm that is strange, if you are truly installing v1.1.0 then both your local copy in vendor and external one here should match..

**Comment by zhsolutions** [comment]
I do not disagree...BUT i can tell you the composer file, the locked file both confirm its 1.1.0
I also uninstalled & deleted any record of the old installation before  running the new ccommand..

Seems likes its downloading some sort of old cache of the files rather then the actual files.

IDK, i manually overwrote the files with the downloaded ones from the .zip.

Seems as though that worked

**Comment by NikolaGavric94** [comment]
@zhsolutions try running `composer clearcache nikolag/square nikolag/core` and then remove vendor, composer.lock and do composer install

**Comment by NikolaGavric94** [comment]
@zhsolutions if the above solution worked, please close the issues

**Comment by NikolaGavric94** [comment]
@zhsolutions closing the issues since u are not responding I take it that you've resolved the issue, feel free to reopen it if it appears again
