### ISSUE TITLE
Database Migration Error

### ISSUE THREAD

**Issue by scottycam** [NikolaGavric94/nikolag-square#12]
I added the package to my project, setup and migrated. However running the migration command fails. 

I am using MySQL ver 14.14

The failure was caused by this line in the "create_nikolag_customers_table" migration.

"$table->string('payment_service_type', 25)->unsigned();"

From my understanding you can't unsign a string. Removing "->unsigned()" fixes my issue. 

ps. Thanks for the package, it is going to save me a lot of time.

**Comment by NikolaGavric94** [comment]
Hello, regarding the issue u were facing it was fixed in the latest version of [nikolag/core](https://github.com/NikolaGavric94/nikolag-core) package, you can look at the latest version and what was fixed (here)[https://github.com/NikolaGavric94/nikolag-core/releases]. Try downloading/updating to the latest version and closing this issue if it resolves ur problem.

I'm glad I was able to contribute :)

**Comment by scottycam** [comment]
Amazing response speed :)

This does fix my problem. However installing the Square package via composer seems to always use core v1.0 (which has the typo). I can manually update core by changing the version in composer.json to 1.0.2 
 and "composer update" however this causes it to trigger the minimum stability issue warning for the square package stating it requires core v1.0 and wont allow the update. Manually updating Core to 1.0.2 fixes my issue though but wasn't able to achieve the update via composer

New install of either core or square packages are installing core 1.0 instead of the updated 1.0.2

**Comment by NikolaGavric94** [comment]
Hmm, can you try doing `composer clearcache` and then doing `composer update`? If this doesn't fixes the issue, I'll push a fix immediatelly

**Comment by scottycam** [comment]
I ran both those commands and had the same issue.

**Comment by scottycam** [comment]
if it helps at all changing the composer.json version of core to 1.0.2 and running composer update. This is the error.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - nikolag/square v1.1.0 requires nikolag/core 1.0.0 -> satisfiable by nikolag/core[v1.0.0] but these conflict with your requirements or minimum-stability.
    - nikolag/square v1.1.0 requires nikolag/core 1.0.0 -> satisfiable by nikolag/core[v1.0.0] but these conflict with your requirements or minimum-stability.
    - Installation request for nikolag/square ^1.1 -> satisfiable by nikolag/square[v1.1.0].

**Comment by NikolaGavric94** [comment]
@scottycam I've just pushed a fix, it passes the tests and installs v1.0.2 of nikolag/core package, could you confirm this actually fixed ur issue?

**Comment by scottycam** [comment]
@NikolaGavric94 I just ran composer update and it didn't update to core 1.0.2. I ran composer clearcache and tried again but same thing.

To test I installed a fresh copy of laravel 5.5 and ran "composer require nikolag/square --dev" to install nikolag/square 

it installed nikolag/core as a dependency but it installed core version 1.0.0 that has the typo. Does the composer.json file for nikolag/square containing the line "nikolag/core": "1.0.0"  under "required" need to be update?

**Comment by NikolaGavric94** [comment]
@scottycam Fresh install should be installing the latest version, because ^1.0 is supposed to install the version `>= 1.0 < 2.0.0` as in https://getcomposer.org/doc/articles/versions.md#caret-version-range-, 
and in the tests that were ran 8h ago it did indeed install as u can see in the image below..
![test](https://user-images.githubusercontent.com/12602403/32431845-53df55c8-c2d5-11e7-955f-292b9cb0a950.PNG)

I'll start a fresh project myself too and i'll try to locate the issue

**Comment by NikolaGavric94** [comment]
@scottycam i've just tried to clearcache and run composer install
<img width="373" alt="screen shot 2017-11-06 at 18 19 31" src="https://user-images.githubusercontent.com/12602403/32454375-5c2bacbe-c31f-11e7-91ca-32337e33ac81.png">
I think you should be fine now, try updating the dependencies with `composer update`

**Comment by scottycam** [comment]
Running "composer update" again this morning and it updates correctly. Also tested on that fresh laravel installation I made before deleting it and updated that too, so all good. Thanks @NikolaGavric94 for helping me and fixing the issue so quickly :)
