### ISSUE TITLE
How to create an order?

### ISSUE THREAD

**Issue by Chris1904** [NikolaGavric94/nikolag-square#13]
Hi there,

thanks for this package! I am currently trying to implement it into my ordering platform. Essentially, what I am looking for is trying to find a way to create an online order so it will show up in my POS along with all the offline orders.

Almost all of the online orders do not need to be paid for. Hence, I only need to create the order, and no charge I assume.

What would you recommend doing in a scenario like this?

Thanks so much Nikola!

Chris

**Comment by NikolaGavric94** [comment]
Hello Chris,

Currently the order system is in place but it’s not yet activated since it needs some more testing, the order system will probably be fully functional in the upcoming versions, roughly by the end of January 2018

Best regards,
Nikola Gavric

**Comment by Chinese1904** [comment]
Thanks Nikola! Looking forward to that :-) 

Best,
Chris

**Comment by NikolaGavric94** [comment]
@Chris1904 Could you contact me via email regarding this feature, thanks

**Comment by NikolaGavric94** [comment]
Implemented as of [v2.0.0](https://github.com/NikolaGavric94/nikolag-square/releases/tag/v2.0.0)
