### ISSUE TITLE
Got error

### ISSUE THREAD

**Issue by koliali** [NikolaGavric94/nikolag-square#14]
i got undefined merchant issue can any one help
![capture](https://user-images.githubusercontent.com/18602107/38350633-8c546acc-38c5-11e8-8f91-41aeed6d5b64.PNG)

**Comment by NikolaGavric94** [comment]
Hello @koliali , `$merchant` represents the object which uses `HasCustomers` Trait, I suppose that is the User class in your case

**Comment by koliali** [comment]
brother do you have any working project for square up integration

**Comment by NikolaGavric94** [comment]
This is a library, I have my local testing application which uses this package, for testing purposes only

**Comment by NikolaGavric94** [comment]
Feel free to reopen issue if you haven't resolved it yet, but provide us with a little more details on the error you are encountering.
