### ISSUE TITLE
DB Tables not found

### ISSUE THREAD

**Issue by zhsolutions** [NikolaGavric94/nikolag-square#9]
Hi!

I just installed your package again, into my project after following the installation instructions when trying to charge a card I get 

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nikolag_transactions' ...

But I cant even find the migrations to create the tables....

**Comment by NikolaGavric94** [comment]
What version are u using?

**Comment by zhsolutions** [comment]
Latest Laravel and this adddon. Im closing this because I did not realize the old install ran the migration and was not be rerun because if it.. However I am experiencing some other bugs, related to the charge method.. I am submmitting now.
